language: r

sudo: true
pandoc: false
latex: false
cache:
  - packages
  - /tmp/texlive
  - /$HOME/.texlive
warnings_are_errors: false

r_binary_packages:
  - data.table
  - magrittr
  - fastmatch
  - stringi
  - Rcpp
  - zoo

r_packages:
  - clisymbols
  - crayon

addons:
  apt:
    packages:
      - libhunspell-dev
      # - hunspell-en-au Wait :-)

#before_install:
  #- source ./travis/texlive.sh
  #- tlmgr install acronym bigfoot blindtext chngcntr cmap nowidow mdframed navigator needspace tablefootnote tocloft xpatch multirow bbding mathastext isomath relsize
  #- tlmgr update --all
  #- sudo apt-get update
  #- sudo apt-get install texlive-bibtex-extra

install: echo Installation step #do not remove this line!

before_script:
    # as somehow no biber package is available for ubuntu 12.04 via apt, let's just download it directly
    # - wget "http://downloads.sourceforge.net/project/biblatex-biber/biblatex-biber/0.9.9/binaries/Linux/biber-linux_x86_64.tar.gz"
  - Rscript -e 'if (!requireNamespace("Rcpp", quietly = TRUE)) system("sudo apt-get install -y r-cran-Rcpp")'
  - Rscript -e 'if (!requireNamespace("zoo", quietly = TRUE)) system("sudo apt-get install -y r-cran-zoo")'
  - Rscript -e 'if (!requireNamespace("devtools", quietly = TRUE)) system("sudo apt-get install -y r-cran-devtools")'
  - Rscript -e 'if (!requireNamespace("hunspell", quietly = TRUE)) system("sudo apt-get install -y r-cran-hunspell")'
  - Rscript -e 'if (!requireNamespace("crayon", quietly = TRUE)) system("sudo apt-get install -y r-cran-crayon")'
  - Rscript -e 'if (!requireNamespace("tinytex", quietly = TRUE)) devtools::install_github("yihui/tinytex")'
  - Rscript -e 'tinytex::install_tinytex()'
  - tlmgr install acronym bigfoot blindtext chngcntr cmap nowidow mdframed navigator needspace tablefootnote tocloft xpatch multirow bbding mathastext isomath relsize

  - wget http://mirrors.ctan.org/biblio/biber/binaries/Linux/biber-linux_x86_64.tar.gz
  - tar xzf biber-linux_x86_64.tar.gz
  - export PATH=$PATH:$PWD
  - tlmgr update biber
  - Rscript -e 'if (!requireNamespace("fastmatch", quietly = TRUE)) install.packages(c("fastmatch", "knitr"))'
  - Rscript -e 'if (!requireNamespace("data.table", quietly = TRUE)) install.packages(c("data.table"))'
  - Rscript -e 'if (!requireNamespace("magrittr", quietly = TRUE)) install.packages(c("magrittr"))'
  - Rscript -e 'devtools::install_github("hughparsonage/hutils")'
  - Rscript -e 'devtools::install_github("hughparsonage/TeXCheckR")'
  - Rscript -e 'devtools::install_github("hughparsonage/grattanReporter")'

script:
  - set -e
  - Rscript -e 'tinytex::pdflatex("Report.tex")'
  - Rscript -e 'library(grattanReporter);checkGrattanReport(compile = TRUE, pre_release = FALSE, .proceed_after_rerun = 3)'


