# DO NOT CHANGE the "init" and "install" sections below
image: Visual Studio 2017

# Download script file from GitHub
install:
  - ps: choco install -y miktex
  - cmd:  refreshenv
  
  

cache:
  - C:\RLibrary
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

# Adapt as necessary starting from here

build_script:
  cmd: 
  - pdflatex -draftmode Report.tex
  - biber Report

test_script:
  # - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
